In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [57]:
df = pd.read_csv("creditcard.csv")

In [53]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62    0.0  
1  0.125895 -0.008983  0.014724    2.69    0.0  
2 -0.139097 -0.055353 -0.059752  378.66    0.0  
3 -0.221929  0.062723  0.061458  123.50    0.0  
4  0.502292  0.219422  0.215153   69.99    0.0  

[5 rows x 31 columns]

In [58]:
df.shape

(284807, 31)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126842 entries, 0 to 126841
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    126842 non-null  int64  
 1   V1      126842 non-null  float64
 2   V2      126842 non-null  float64
 3   V3      126842 non-null  float64
 4   V4      126842 non-null  float64
 5   V5      126842 non-null  float64
 6   V6      126842 non-null  float64
 7   V7      126842 non-null  float64
 8   V8      126842 non-null  float64
 9   V9      126841 non-null  float64
 10  V10     126841 non-null  float64
 11  V11     126841 non-null  float64
 12  V12     126841 non-null  float64
 13  V13     126841 non-null  float64
 14  V14     126841 non-null  float64
 15  V15     126841 non-null  float64
 16  V16     126841 non-null  float64
 17  V17     126841 non-null  float64
 18  V18     126841 non-null  float64
 19  V19     126841 non-null  float64
 20  V20     126841 non-null  float64
 21  V21     12

In [59]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [60]:
df.describe

<bound method NDFrame.describe of             Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599

In [61]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [62]:
for i in df.columns:
    print(i,"-------->",df[i].corr(df['Class']))

Time --------> -0.012322570929245642
V1 --------> -0.10134729859508508
V2 --------> 0.09128865034461915
V3 --------> -0.19296082706741322
V4 --------> 0.13344748623900432
V5 --------> -0.09497429899144809
V6 --------> -0.043643160699963775
V7 --------> -0.18725659151429797
V8 --------> 0.019875123914794363
V9 --------> -0.09773268607407871
V10 --------> -0.21688294364102725
V11 --------> 0.1548756447439473
V12 --------> -0.26059292487721686
V13 --------> -0.004569778799461258
V14 --------> -0.3025436958044044
V15 --------> -0.004223402267856669
V16 --------> -0.1965389403040179
V17 --------> -0.32648106724371434
V18 --------> -0.11148525388904092
V19 --------> 0.03478301303651474
V20 --------> 0.020090324196975373
V21 --------> 0.04041338061057561
V22 --------> 0.0008053175052984613
V23 --------> -0.002685155740250693
V24 --------> -0.007220906715952716
V25 --------> 0.0033077055972996422
V26 --------> 0.004455397501283351
V27 --------> 0.017579728189513248
V28 --------> 0.009536040916

In [63]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

# Train Test Split
from sklearn.model_selection import train_test_split

# Metrics
from sklearn.metrics import confusion_matrix, accuracy_score

# Models
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [64]:
y = df['Class']
x = df.drop(['Class'],axis = 1)

In [65]:
x.shape,y.shape

((284807, 30), (284807,))

In [66]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=2)

In [68]:
lst = [x_train,x_test,y_train,y_test]
for data in lst:
  print("shape","---->",data.shape)

shape ----> (227845, 30)
shape ----> (56962, 30)
shape ----> (227845,)
shape ----> (56962,)


In [69]:
mdl_1 = make_pipeline(StandardScaler(), KNeighborsClassifier())
mdl_2 = make_pipeline(StandardScaler(), LogisticRegression())
mdl_3 = make_pipeline(StandardScaler(), SVC())
mdl_4 = make_pipeline(StandardScaler(), DecisionTreeClassifier())
mdl_5 = make_pipeline(StandardScaler(), RandomForestClassifier())

In [70]:
mdl_lst = [mdl_1,mdl_2,mdl_3,mdl_4,mdl_5]
accuracy_lst = []
for mdl in mdl_lst:
  i = 1
  mdl.fit(x_train, y_train)
  y_pred = mdl.predict(x_test)
  print("")
  print("******CLASSIFICATION MODEL******")
  i = i+1
  print("")
  print("CONFUSION MATRIX")
  print(confusion_matrix(y_test,y_pred))
  print("")
  print("ACCURACY SCORE")
  print(accuracy_score(y_test,y_pred))
  print("----------------------------")
  accuracy_lst.append(accuracy_score(y_test,y_pred))



******CLASSIFICATION MODEL******

CONFUSION MATRIX
[[56873     5]
 [   16    68]]

ACCURACY SCORE
0.9996313331694814
----------------------------

******CLASSIFICATION MODEL******

CONFUSION MATRIX
[[56871     7]
 [   24    60]]

ACCURACY SCORE
0.9994557775359011
----------------------------

******CLASSIFICATION MODEL******

CONFUSION MATRIX
[[56874     4]
 [   20    64]]

ACCURACY SCORE
0.9995786664794073
----------------------------

******CLASSIFICATION MODEL******

CONFUSION MATRIX
[[56856    22]
 [   19    65]]

ACCURACY SCORE
0.9992802219023208
----------------------------

******CLASSIFICATION MODEL******

CONFUSION MATRIX
[[56873     5]
 [   15    69]]

ACCURACY SCORE
0.9996488887328394
----------------------------


In [71]:
print(accuracy_lst.index(max(accuracy_lst)))



4
